#!/usr/bin/env tclsh
# tools/x.tcl — the els task runner.  ALL project tooling lives here (Tcl), plus
# C built by the vendored gcc.  Normally invoked through x.cmd (which sets PATH
# to the vendored toolchain first); this script re-asserts PATH itself so it is
# also robust when run directly with the vendored tclsh.

set ROOT [file normalize [file join [file dirname [info script]] ..]]
set TC   [file join $ROOT .toolchain]

# Make the vendored toolchain win on PATH (idempotent with x.cmd).  Git is
# optional (the app and core tooling do not use it) — only added if vendored.
set vbins {}
foreach b [list [file join $TC msys64 ucrt64 bin] [file join $TC tcl9 bin] \
                [file join $TC git cmd]] {
    if {[file isdirectory $b]} { lappend vbins [file nativename $b] }
}
if {[llength $vbins]} { set ::env(PATH) "[join $vbins {;}];$::env(PATH)" }
if {![info exists ::env(MSYSTEM)]} { set ::env(MSYSTEM) UCRT64 }

# the vendored curl (used by the fetch tasks), or PATH curl as a fallback
proc curl-exe {} {
    foreach c [list [TCp msys64 usr bin curl.exe] [TCp msys64 ucrt64 bin curl.exe]] {
        if {[file exists $c]} { return $c }
    }
    return curl
}

# ---- path helpers -------------------------------------------------------
proc P  {args} { return [file join $::ROOT {*}$args] }
proc TCp {args} { return [file join $::TC {*}$args] }
proc tclsh {} { return [TCp tcl9 bin tclsh90.exe] }
proc wish  {} { return [TCp tcl9 bin wish90.exe] }
proc gcc   {} { return [TCp msys64 ucrt64 bin gcc.exe] }

proc stream {args} { exec {*}$args >@ stdout 2>@ stderr }

# Cheap per-command guard: a task declares the tool(s) it needs; we only check
# those exist (a microsecond `file exists`, NOT a full toolchain scan), and
# point at `x toolcheck` if one is missing.
proc tool_path {tool} {
    switch $tool {
        tclsh { return [tclsh] }
        wish  { return [wish] }
        gcc   { return [gcc] }
        twapi { return [TCp twapi-dl twapi-5.2.0 pkgIndex.tcl] }
        default { return "" }
    }
}
proc need {args} {
    foreach tool $args {
        set p [tool_path $tool]
        if {$p eq "" || ![file exists $p]} {
            error "required tool '$tool' is missing — run: x toolcheck --prep"
        }
    }
}

# ---- tasks --------------------------------------------------------------
proc task_help {args} {
    puts {els task runner — usage: x <command> [args]

  test               run the in-process test suite (tcltest + event generate)
  run [file ...]     launch the editor (wish + els.tcl)
  shot <out> [file]  screenshot the editor to <out> (twapi)
  build-ext          compile the C23 extension(s) in src/ -> build/*.dll
  fetch-twapi        vendor the twapi extension into .toolchain/
  fetch-git          vendor MinGit into .toolchain/git/
  toolcheck [--prep] check the vendored toolchain (--prep fetches what's missing)
  env                print the resolved toolchain paths + versions
  help               this message}
}

proc task_env {args} {
    puts "ROOT  = $::ROOT"
    foreach {label path} [list tclsh [tclsh] wish [wish] gcc [gcc]] {
        puts [format "  %-6s %s  (%s)" $label $path \
            [expr {[file exists $path] ? "ok" : "MISSING"}]]
    }
    set git [TCp git cmd git.exe]
    puts [format "  %-6s %s  (%s)" git $git \
        [expr {[file exists $git] ? "ok" : "optional — run `x fetch-git`"}]]
    catch {puts "  gcc   [exec [gcc] -dumpversion]"}
    catch {puts "  tcl   [exec [tclsh] << {puts [info patchlevel]}]"}
    if {[file exists $git]} { catch {puts "  git   [exec $git --version]"} }
}

proc task_toolcheck {args} {
    stream [tclsh] [P tools toolcheck.tcl] {*}$args
}

proc task_test {args} {
    need tclsh
    stream [tclsh] [P tests run.tcl] {*}$args
}

proc task_run {args} {
    need wish
    exec [wish] [P els.tcl] {*}$args &
    puts "launched els"
}

proc task_shot {args} {
    need tclsh wish twapi
    if {[llength $args] < 1} { error "usage: x shot <out.png> \[file ...\]" }
    set out [lindex $args 0]
    stream [tclsh] [P tools shot.tcl] [wish] [P els.tcl] $out {*}[lrange $args 1 end]
}

# Compile every src/*.c into build/<name>.dll against the Tcl stubs, and emit a
# pkgIndex.tcl so `package require <name>` works.  Init proc = Titlecased name
# (elsx.c -> Elsx_Init), matching Tcl's load convention.
proc task_build-ext {args} {
    need gcc tclsh
    set inc [TCp tcl9 include]
    set lib [TCp tcl9 lib]
    file mkdir [P build]
    set sources [lsort [glob -nocomplain -directory [P src] *.c]]
    if {![llength $sources]} { puts "no src/*.c to build"; return }
    set idx [open [P build pkgIndex.tcl] w]
    puts $idx "# auto-generated by `x build-ext` — do not edit"
    foreach src $sources {
        set name [file rootname [file tail $src]]
        set dll  [P build $name.dll]
        set init [string totitle $name]
        puts "cc  [file tail $src] -> build/$name.dll"
        stream [gcc] -std=c23 -O2 -Wall -shared -DUSE_TCL_STUBS \
            -I$inc $src -o $dll -L$lib -ltclstub -static-libgcc
        puts $idx "package ifneeded $name 0.1 \[list load \[file join \$dir $name.dll\] $init\]"
    }
    close $idx
    puts "built [llength $sources] extension(s); wrote build/pkgIndex.tcl"
}

proc task_fetch-twapi {args} {
    set ver 5.2 ; set zip twapi-5.2.0.zip
    set dest [TCp twapi-dl]
    if {[file exists [file join $dest twapi-5.2.0 pkgIndex.tcl]]} {
        puts "twapi already vendored at [file join $dest twapi-5.2.0]"
        return
    }
    file mkdir $dest
    set zpath [file join $dest $zip]
    puts "downloading twapi $ver ..."
    stream [curl-exe] -L --fail -o $zpath \
        "https://github.com/apnadkarni/twapi/releases/download/v$ver/$zip"
    # extract with Tcl's own zipfs (no external unzip needed)
    set mp /twapi_extract
    catch {zipfs unmount $mp}
    zipfs mount $zpath $mp
    file copy -force //zipfs:$mp/twapi-5.2.0 [file join $dest twapi-5.2.0]
    zipfs unmount $mp
    file delete -force $zpath
    puts "twapi $ver vendored at [file join $dest twapi-5.2.0]"
}

# Optional: vendor MinGit (git-for-windows' slim, embeddable, GUI-less build) so
# the project folder is self-contained on a machine without git.  Not needed by
# the app or the build/test tooling.  Pass a MinGit zip URL, or use the default.
proc task_fetch-git {args} {
    set url [lindex $args 0]
    if {$url eq ""} {
        set url "https://github.com/git-for-windows/git/releases/download/v2.54.0.windows.1/MinGit-2.54.0-64-bit.zip"
    }
    set dest [TCp git]
    if {[file exists [TCp git cmd git.exe]]} { puts "git already vendored at $dest"; return }
    file mkdir $dest
    set zpath [file join $::TC mingit.zip]
    puts "downloading MinGit from $url ..."
    stream [curl-exe] -L --fail -o $zpath $url
    set mp /mingit
    catch {zipfs unmount $mp}
    zipfs mount $zpath $mp
    foreach item [glob -nocomplain -tails -directory //zipfs:$mp *] {
        file copy -force //zipfs:$mp/$item [file join $dest $item]
    }
    zipfs unmount $mp
    file delete -force $zpath
    puts "MinGit vendored at $dest"
}

# ---- dispatch -----------------------------------------------------------
set cmd [lindex $argv 0]
if {$cmd eq ""} { set cmd help }
set proc "task_$cmd"
if {[llength [info commands $proc]] == 0} {
    puts stderr "x: unknown command '$cmd' (try: x help)"
    exit 2
}
if {[catch {$proc {*}[lrange $argv 1 end]} err]} {
    puts stderr "x $cmd: $err"
    exit 1
}
